/**
 * @file SdTileMapProvider.h
 * @brief Reads pre-rendered RGB565 tiles from the SD card and composes a
 *        viewport image — no WiFi or internet required.
 *
 * Tile layout (generated by tools/split_map.py --bounds ...):
 *   /map/config.txt           — see below
 *   /map/tile_RRR_CCC.bin     — raw RGB565, tileSize×tileSize px (little-endian)
 *
 * config.txt format (three lines):
 *   <totalWidth>,<totalHeight>
 *   <latTop>,<lonLeft>,<latBottom>,<lonRight>
 *   <tileSize>
 *
 * fetch() composes a viewport of out.w × out.h pixels centred on (lat, lon)
 * from however many tiles are needed, then fills out.bounds with the exact
 * geographic extents of that viewport.  zoom is ignored (baked into the tiles).
 */
#ifndef MAP_SD_TILE_MAP_PROVIDER_H
#define MAP_SD_TILE_MAP_PROVIDER_H

#include <cstdint>

#include "map/IMapImageProvider.h"

namespace gmap {

class SdTileMapProvider : public IMapImageProvider {
public:
    SdTileMapProvider() = default;

    /**
     * Mount the SD card and read config.  Must be called once before fetch().
     * Returns true if the SD card is present and config.txt is valid.
     */
    bool begin();

    bool fetch(double lat, double lon, uint8_t zoom, MapImage& out) override;

    /** Returns the geographic centre of the loaded tile set. */
    bool getDefaultPosition(double& lat, double& lon) override {
        if (!configLoaded_) return false;
        lat = (latTop_ + latBottom_) * 0.5;
        lon = (lonLeft_ + lonRight_) * 0.5;
        return true;
    }

    bool isReady() const { return mounted_ && configLoaded_; }

private:
    bool mount();
    bool loadConfig();

    /** Copy the pixels of one tile that overlap the viewport into out.data. */
    void blitTile(int32_t tileRow, int32_t tileCol,
                  int32_t vpLeft, int32_t vpTop,
                  const MapImage& out);

    bool mounted_      = false;
    bool configLoaded_ = false;

    int32_t totalW_    = 0;
    int32_t totalH_    = 0;
    int32_t tileSize_  = 256;
    double  latTop_    = 0;
    double  lonLeft_   = 0;
    double  latBottom_ = 0;
    double  lonRight_  = 0;

    /* Reusable row buffer (stack-allocated, max tile row = 512 px × 2 bytes). */
    static constexpr int kMaxTileSize = 512;
    uint8_t rowBuf_[kMaxTileSize * 2]{};
};

}  // namespace gmap

#endif /* MAP_SD_TILE_MAP_PROVIDER_H */
