/**
 * @file SdXyzTileProvider.h
 * @brief Reads standard XYZ slippy-map tiles from the SD card.
 *
 * Tile layout on SD card (generated by tools/download_tiles.py):
 *   /tiles/<zoom>/<x>/<y>.bin   — raw RGB565, 256×256 px, little-endian
 *
 * Uses the standard Web Mercator (EPSG:3857) projection — identical to
 * OpenStreetMap, Google Maps, Bing, etc. Any XYZ tile source works.
 *
 * fetch() reads 1–6 tiles per call (no row-by-row seeks, whole-tile reads)
 * and composites them into the output viewport buffer in PSRAM.
 */
#ifndef MAP_SD_XYZ_TILE_PROVIDER_H
#define MAP_SD_XYZ_TILE_PROVIDER_H

#include <cstdint>

#include "map/IMapImageProvider.h"

namespace gmap {

class SdXyzTileProvider : public IMapImageProvider {
public:
    SdXyzTileProvider()  = default;
    ~SdXyzTileProvider();

    /**
     * Mount SD and verify the /tiles directory.
     * Must be called once before fetch(). Returns false on failure.
     */
    bool begin();

    bool fetch(double lat, double lon, uint8_t zoom, MapImage& out) override;

    /** Returns centre of the bounding box used during download. */
    bool getDefaultPosition(double& lat, double& lon) override;

    bool isReady() const { return mounted_; }

    /**
     * Optionally store the download bounding box so getDefaultPosition()
     * has a sensible value even before the first fetch().
     */
    void setDefaultCenter(double lat, double lon) {
        defaultLat_ = lat; defaultLon_ = lon; hasDefault_ = true;
    }

private:
    bool   mountSd();

    /* Web Mercator helpers */
    static void latLonToGlobalPixel(double lat, double lon, int zoom,
                                    double& gpx, double& gpy);
    static void globalPixelToLatLon(double gpx, double gpy, int zoom,
                                    double& lat, double& lon);

    /* Read one 256×256 RGB565 tile into tileBuf_. Returns false if missing. */
    bool loadTile(int zoom, int tx, int ty);

    /* Copy loaded tile pixels that overlap the viewport into out. */
    void blitTile(int zoom, int tx, int ty,
                  int32_t vpGpxLeft, int32_t vpGpyTop,
                  const MapImage& out);

    bool     mounted_    = false;

    double   defaultLat_ = 0, defaultLon_ = 0;
    bool     hasDefault_ = false;

    static constexpr int kTilePx = 256;

    /* One tile buffer in PSRAM — reused across blitTile() calls. */
    uint8_t* tileBuf_  = nullptr;    /* kTilePx*kTilePx*2 bytes */
    int      loadedTx_ = -1, loadedTy_ = -1, loadedZoom_ = -1;
};

}  // namespace gmap

#endif /* MAP_SD_XYZ_TILE_PROVIDER_H */
