/**
 * @file AppConfig.h
 * @brief All user-tunable settings in one place, persisted to NVS.
 *
 * Single responsibility: hold configuration and (de)serialize it. Subsystems
 * receive the values they need by reference; they never read NVS themselves.
 *
 * WiFi credentials and host addresses default to placeholders — edit them here
 * (or change at runtime + save()) for your network.
 */
#ifndef APP_CONFIG_H
#define APP_CONFIG_H

#include <cstdint>

namespace app {

struct AppConfig {
    /* WiFi station */
    char     wifiSsid[33] = "DatNguyen";
    char     wifiPass[65] = "11111111";

    /* PC map tool (tools/map_server.py) */
    char     pcHost[40]   = "192.168.3.45";
    uint16_t pcPort       = 8080;

    /* Forward target (real ground station, e.g. Mission Planner UDP in) */
    char     gcsIp[40]    = "192.168.3.255";  /* default: /24 broadcast */
    uint16_t gcsPort      = 14550;

    /* Link */
    bool     linkSourceUsb = false;   /* false = UART, true = USB-CDC */
    uint32_t telemBaud     = 57600;

    /* Forward */
    bool     forwardEnabled = false;

    /* Map (held in PSRAM, larger than the screen for pan headroom) */
    uint16_t mapW         = 1024;
    uint16_t mapH         = 1024;
    uint8_t  mapZoom      = 17;
    uint16_t edgeMarginPx = 150;      /* re-fetch when marker within this of edge */

    /**
     * Map source selection:
     *   0 = WiFi (tools/map_server.py over LAN)
     *   1 = SD card split tiles  (/map/tile_RRR_CCC.bin, generated by split_map.py)
     *   2 = SD card XYZ tiles    (/tiles/Z/X/Y.bin, generated by download_tiles.py)
     *       This mode uses standard Web Mercator — works with OSM or any XYZ source.
     */
    uint8_t  mapSource    = 2;   /* default: SD XYZ tiles */

    /* Default map centre for XYZ mode (shown before any GPS fix).
     * Set to the centre of your downloaded tile area. */
    double   defaultLat   = 21.0746;   /* centre of Hanoi test area — change to yours */
    double   defaultLon   = 105.7890;


    /** Load persisted values from NVS (keeps defaults for missing keys). */
    void load();
    /** Persist current values to NVS. */
    void save() const;
};

}  // namespace app

#endif /* APP_CONFIG_H */
